### ISSUE TITLE
"label is not defined" bug when using "Int" type "internal IDs"

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/single-page-app-codegen#78]
When using an `Int` "internal ID" or `[Int]` foreign key arrays the following error occurs:

```sh
label is not defined                         
    at eval (/home/hallab/projects/untwist-db/single-page-app-codegen/views/pages/model-table/components/model-create-panel/components/model-attr
ibutes-page/model-attributes-form-view/ModelAttributesFormView.ejs:167:17)
    at ModelAttributesFormView (/home/hallab/projects/untwist-db/single-page-app-codegen/node_modules/ejs/lib/ejs.js:691:17)
    at tryHandleCache (/home/hallab/projects/untwist-db/single-page-app-codegen/node_modules/ejs/lib/ejs.js:272:36)
    at exports.renderFile (/home/hallab/projects/untwist-db/single-page-app-codegen/node_modules/ejs/lib/ejs.js:489:10)
    at internal/util.js:297:30                                                                                                   
    at new Promise (<anonymous>)      
    at internal/util.js:296:12         
    at Object.exports.renderTemplate (/home/hallab/projects/untwist-db/single-page-app-codegen/funks.js:20:18)
    at Object.exports.renderToFileSync (/home/hallab/projects/untwist-db/single-page-app-codegen/funks.js:70:31)
    at Object.exports.genSpa (/home/hallab/projects/untwist-db/single-page-app-codegen/funks.js:2174:19) {
  path: '/home/hallab/projects/untwist-db/single-page-app-codegen/views/pages/model-table/components/model-create-panel/components/model-attribut
es-page/model-attributes-form-view/ModelAttributesFormView.ejs'
}
```

_Note_ that the above is an example for a Zendro app called "untwist" and a data model called protocol with an internal ID called "protocol_id" of type "Int".

**Comment by framirez07** [comment]
Fixed in this commit! [92105d7f](https://github.com/Zendro-dev/single-page-app-codegen/commit/92105d7f928ef586ed23c7d2794ed9ba8628ef95)
